services:
  # --- Servicio del Backend (Spring Boot) ---
  categorias-service:
    build:
      context: ./BACKEND/categorias_service  # CORRECCIÓN: Agregar ./
      dockerfile: Dockerfile  # CORRECCIÓN: Especificar explícitamente
    container_name: unrobot_categorias_service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://unrobot-postgres:5432/unrobot-postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - postgres-db
    networks:
      - unrobot-net

  # --- Servicio de la Base de Datos (PostgreSQL) ---
  postgres-db:
    image: postgres:13
    container_name: unrobot-postgres
    environment:
      POSTGRES_DB: unrobot-postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - unrobot_data:/var/lib/postgresql/data
    networks:
      - unrobot-net

networks:
  unrobot-net:
    driver: bridge

volumes:
  unrobot_data:
    driver: local